spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.30/sell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    com.imooc: debug
server:
  context-path: /sell
wechat:
  mpAppId: wx3dab51bc315e57a4
  mpAppSecret: 21ce7adb5282c78b4c98b3e67a0ed6b3