spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.30/sell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: false
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    com.imooc: debug
#server:
#  context-path: /sell
wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: xxx
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: C:\zjf\code\github\sell\src\main\resources\h5.p12
  notifyUrl: http://hellozjf.natapp1.cc/notify